# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

# How to set up different Java versions: https://github.com/marketplace/actions/setup-java-jdk
    steps:
    - name: Set up JDK 17
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      #uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

# Note for AWS: 
# The IP address changes when turning off and on the service
# An IP address can be set by using an Elastic IP (this is currently not set up)
# The hostname/ec2 instance will need to be changed everytime the service is restarted

    - name: Copy Java jar file to EC2 via SSH Key
      uses: appleboy/scp-action@master
      with:
        host: ec2-18-223-21-118.us-east-2.compute.amazonaws.com
        username: ec2-user
        port: 22
        key: ${{ secrets.ART_APP_KEY }}
        source: "target/CYS-1.0.jar"
        target: "~/"

    - name: Run commands to start the Java server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ec2-18-223-21-118.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.ART_APP_KEY }}
        port: 22
        script: |
          killall java
          nohup java -jar /home/ec2-user/target/CYS-1.0.jar > log.txt &
          sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
          sudo iptables -I INPUT -p tcp --dport 8080 -j ACCEPT

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
